Запрос на добавление тестов на при разделении на роли
ViRGiL175/spring-security-module pull request #7
Opened 2022-03-28 19:23 UTC by EsQLap

2022-03-31 11:01 UTC, ViRGiL175 requested changes
Найс. Этот язык безопасности довольно читаемый.

Оставил несколько соображений, даже в целом по архитектуре. Можно пообсуждать.

2022-03-31 11:01 UTC, ViRGiL175 commented on example/src/main/java/ru/virgil/example/box/BoxController.java
> +        assert boxDto.getType() != null;
Лучше уж везде единообразно юзать `Truth`.

2022-03-31 11:01 UTC, ViRGiL175 commented on example/src/main/java/ru/virgil/example/box/BoxController.java
> +        assert boxDto.getType() != null;
У `Truth` кроме всего прочего довольно читаемый листинг ошибок, если конвертировать ошибки `Truth` в статусы HTTP с протаскиванием листинга ошибки, то может получиться вкусно и информативно.

2022-03-31 11:01 UTC, ViRGiL175 commented on example/src/main/java/ru/virgil/example/box/BoxMockService.java
>      }
Тут неочевидная катастрофа с отложенным таймером.

Я не просто так сначала инициализирую пустые коробки, сохраняю их в БД, а потом уже заполняю отдельно.

Если делать такое массовое заполнение одновременно с инициализацией, в какой-то момент начинаются непонятные ошибки и стековерфлоу.

Это не проявляется сразу, но по ходу наращивания архитектуры. И потом невозможно понять, в чем причина этой сатанины, пока не распутаешь все обратно.

Лучше инициализируй отдельно, заполняй отдельно.

Либо нужно обсудить, если ты понимаешь, почему при одновременной инициализации и заполнении все начинает сходить с ума.

2022-03-31 11:01 UTC, ViRGiL175 commented on example/src/main/java/ru/virgil/example/system/RestResponseExceptionHandler.java
> +    }
Попробуй проверить, когда внедришь `Truth`, передается ли его сообщение об ошибке в описание статуса `BAD_REQUEST` для клиента.

Они тут хвастаются, какие у них красивые отчеты об ошибках, надо юзать по полной.
https://truth.dev/comparison#:~:text=lead%20to%20puzzlers.-,Failure%20messages,-We%20usually%20prefer

2022-03-31 11:01 UTC, ViRGiL175 commented on example/src/test/java/ru/virgil/example/BoxApiTest.java
> +        Truth.assertThat(testDto.getPrice()).isEqualTo(createdDto.getPrice());
Слушай, я вот сейчас подумал...

Ломбок же генерит эквалс для этих ДТОшек. Тогда можно просто сравнить одну эквалс другую, а сравнение полей там уже сгенерено, намного меньше кода получается.

2022-04-07 17:12 UTC, EsQLap commented on example/src/main/java/ru/virgil/example/box/BoxController.java
> +        assert boxDto.getType() != null;
Я помню, мы это обсуждали. Не использовал это, потому что не заработало в тот раз... Но в этот почему-то заработало! Парадокс) Закомиттил.

У меня в прошлый раз сложилось ощущение, что Truth не кидает ошибки. Хз, почему не работало.

2022-04-07 17:23 UTC, EsQLap commented on example/src/main/java/ru/virgil/example/system/RestResponseExceptionHandler.java
> +    }
К сожалению, в Response ничего не записывается :(

2022-04-07 18:24 UTC, EsQLap commented on example/src/main/java/ru/virgil/example/box/BoxMockService.java
>      }
Я вернул всё, как было до этого. Там хватало функционала для полноценной работы. А тип коробки сделал Usual по дефолту.

2022-04-07 18:26 UTC, EsQLap commented on example/src/test/java/ru/virgil/example/BoxApiTest.java
> +        Truth.assertThat(testDto.getPrice()).isEqualTo(createdDto.getPrice());
Проблема со сравнением присутствует и здесь. Пока на этапе решения:
https://github.com/Dreddbook/spring-dreddbook-server/pull/74#discussion_r845021321

2022-05-18 17:38 UTC, EsQLap commented on example/src/test/java/ru/virgil/example/BoxApiTest.java
> +        Truth.assertThat(testDto.getPrice()).isEqualTo(createdDto.getPrice());
Если что, проблема решилась :)

2022-05-20 11:55 UTC, ViRGiL175 commented
Так, все это беру в работу.

2022-05-20 11:57 UTC, merged